CREATE DATABASE IF NOT EXISTS attendance_system;
USE attendance_system;

CREATE TABLE Teachers (
TeacherID INT PRIMARY KEY AUTO_INCREMENT,
TeacherName VARCHAR(100) NOT NULL,
Email VARCHAR(100) UNIQUE NOT NULL,
Phone VARCHAR(15),
Department VARCHAR(50),
CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Classes (
ClassID INT PRIMARY KEY AUTO_INCREMENT,
ClassName VARCHAR(50) NOT NULL,
Semester INT,
Year INT,
TeacherID INT,
CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (TeacherID) REFERENCES Teachers(TeacherID)
ON DELETE SET NULL
ON UPDATE CASCADE
);

CREATE TABLE Students (
StudentID INT PRIMARY KEY AUTO_INCREMENT,
StudentName VARCHAR(100) NOT NULL,
Email VARCHAR(100) UNIQUE NOT NULL,
Phone VARCHAR(15),
ClassID INT,
RollNumber VARCHAR(20) UNIQUE,
CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (ClassID) REFERENCES Classes(ClassID)
ON DELETE SET NULL
ON UPDATE CASCADE
);

CREATE TABLE Subjects (
SubjectID INT PRIMARY KEY AUTO_INCREMENT,
SubjectName VARCHAR(100) NOT NULL,
SubjectCode VARCHAR(20) UNIQUE NOT NULL,
Credits INT DEFAULT 3,
CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ClassSubjects (
ClassSubjectID INT PRIMARY KEY AUTO_INCREMENT,
ClassID INT NOT NULL,
SubjectID INT NOT NULL,
TeacherID INT,
CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (ClassID) REFERENCES Classes(ClassID)
ON DELETE CASCADE
ON UPDATE CASCADE,
FOREIGN KEY (SubjectID) REFERENCES Subjects(SubjectID)
ON DELETE CASCADE
ON UPDATE CASCADE,
FOREIGN KEY (TeacherID) REFERENCES Teachers(TeacherID)
ON DELETE SET NULL
ON UPDATE CASCADE,
UNIQUE KEY unique_class_subject (ClassID, SubjectID)
);

CREATE TABLE Attendance (
AttendanceID INT PRIMARY KEY AUTO_INCREMENT,
StudentID INT NOT NULL,
SubjectID INT NOT NULL,
AttendanceDate DATE NOT NULL,
Status ENUM('Present', 'Absent', 'Late', 'Excused') NOT NULL,
Remarks TEXT,
CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (StudentID) REFERENCES Students(StudentID)
ON DELETE CASCADE
ON UPDATE CASCADE,
FOREIGN KEY (SubjectID) REFERENCES Subjects(SubjectID)
ON DELETE CASCADE
ON UPDATE CASCADE,
UNIQUE KEY unique_attendance (StudentID, SubjectID, AttendanceDate)
);
